parameters:
    functionaltest.cache_sqlite_db: false
    functionaltest.html5validationurl: http://validator.nu/
    functionaltest.authentication:
        username: foo@bar.com
        password: 12341234
