languages:
  PHP: true

ratings:
  paths:
    - Annotations/*
    - DependencyInjection/*
    - DependencyInjection/Compiler/*
    - EventListener/*
    - Exception/*
    - Test/*
    - Validator/*

exclude_paths:
  - DataFixtures/ORM/*
  - Tests/App/*
