checks:
  php:
    code_rating: true
    duplication: true

filter:
  excluded_paths:
    - Tests/*
  paths:
    - Annotations/*
    - DependencyInjection/*
    - DependencyInjection/Compiler/*
    - EventListener/*
    - Exception/*
    - Test/*
    - Validator/*

build:
  dependencies:
    override:
      - "composer self-update"
      - "composer install --no-interaction -vvv"
  tests:
    override:
      -
        command: 'phpunit --coverage-clover=coverage-clover'
        coverage:
          file: 'coverage-clover'
          format: 'php-clover'
